services:

  web:
    image: nginx
    expose:
      - "80"
    volumes:
      - ./code:/usr/share/nginx/html
    ports:
      - "8080:80"

  mariadb:
    image: "mariadb:latest"
    restart: "always"
    volumes:
      - "./data:/var/lib/mysql/data"
      - "./logs:/var/lib/mysql/logs"
      - "/var/docker/mariadb/conf:/etc/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=heticdb
      - MYSQL_USER=hetic
      - MYSQL_PASSWORD=hetic

  phpmyadmin:
    image: phpmyadmin
    restart: "always"
    ports:
      - "40001:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306

  wordpress:
    image: wordpress
    ports:
      - "8081:80"  # Changed to avoid conflict
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=heticdb
      - WORDPRESS_DB_USER=hetic
      - WORDPRESS_DB_PASSWORD=hetic
    volumes:
      - "./wordpress:/var/www/html"
